version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: "npm"
    directory: "/tracker"
    schedule:
      interval: "daily"
    buka-tarik-permintaan-batas: 1
<script defer data-domain="cair77.net" src="https://plausible.io/js/script.js"></script>
